### ISSUE TITLE
AttributeError: 'RequestOutput' object has no attribute 'value_estimate'

### ISSUE THREAD

**Issue by yanzhenqiang** [MARIO-Math-Reasoning/Super_MARIO#10]
run “python solver_demo.py --custom_cfg configs/sbs_sft.yaml --qaf ../MARIO_EVAL/data/math_testset_annotation.json”，and then get the error above，how to fix？

**Comment by lovecambi** [comment]
> run “python solver_demo.py --custom_cfg configs/sbs_sft.yaml --qaf ../MARIO_EVAL/data/math_testset_annotation.json”，and then get the error above，how to fix？

Did you follow the [installation](https://github.com/MARIO-Math-Reasoning/Super_MARIO?tab=readme-ov-file#installation) in readme? You need to install the modified vllm.
