### ISSUE TITLE
Why not directly generate the value, but instead add a value head? Could you explain the reasoning behind this decision?

### ISSUE THREAD

**Issue by yanzhenqiang** [MARIO-Math-Reasoning/Super_MARIO#12]

**Comment by lovecambi** [comment]
No particular reason. Just follow the common practice in RLHF or DPO. To support value model training, we use the package [trl](https://github.com/huggingface/trl/blob/main/trl/models/modeling_value_head.py).

The additional value head can directly be plugged into a pre-trained LLM without hurting the original capability.
