### ISSUE TITLE
Issue about requirements file

### ISSUE THREAD

**Issue by LePanda026** [MARIO-Math-Reasoning/Super_MARIO#18]
I'm sorry to bring up this issue, but I need to install every package that isn't mentioned in the requirements.txt file. Could you please provide a complete requirements.txt file? :(

**Comment by LePanda026** [comment]
i even have to install numpy by myself

**Comment by lovecambi** [comment]
For a quick reply, you can refer to the following cmd.

```bash
> git clone https://github.com/MARIO-Math-Reasoning/Super_MARIO.git
> git clone https://github.com/MARIO-Math-Reasoning/MARIO_EVAL.git
> git clone https://github.com/MARIO-Math-Reasoning/vllm.git

> cd Super_MARIO && pip install -r requirements.txt && cd ..

> cd MARIO_EVAL/latex2sympy && pip install . && cd ..
> pip install -e .

> cd ../vllm
> pip install -e .
```

**Comment by LePanda026** [comment]
> For a quick reply, you can refer to the following cmd.
> 
> ```shell
> > git clone https://github.com/MARIO-Math-Reasoning/Super_MARIO.git
> > git clone https://github.com/MARIO-Math-Reasoning/MARIO_EVAL.git
> > git clone https://github.com/MARIO-Math-Reasoning/vllm.git
> 
> > cd Super_MARIO && pip install -r requirements.txt && cd ..
> 
> > cd MARIO_EVAL/latex2sympy && pip install . && cd ..
> > pip install -e .
> 
> > cd ../vllm
> > pip install -e .
> ```

Thank you! I overlooked the requirements detailed in the README.md. Apologizing for that. Thanks a lot!
