### ISSUE TITLE
Problem running evaluation

### ISSUE THREAD

**Issue by vgaraujov** [MARIO-Math-Reasoning/Super_MARIO#19]
Hello!

I got the following error when running the evaluation script `python eval_output_jsonl.py`:
`2356it [00:56, 48.63it/s]GNU MP: Cannot allocate memory (size=800296713216048)`

This didn't happen to me before when I used B1=1. However, I'm now using B1>=3, I'm getting this error frequently. I'd appreciate any suggestions on this. Thanks!

**Comment by lovecambi** [comment]
Can you try [tip 3](https://github.com/MARIO-Math-Reasoning/MARIO_EVAL?tab=readme-ov-file#requirements)?
