### ISSUE TITLE
Potential Wrong Logic

### ISSUE THREAD

**Issue by sfc-gh-zhyao** [MARIO-Math-Reasoning/Super_MARIO#21]
https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/agents/mcts.py#L69

Should this line be 
```
while node.has_children() and (not node.is_terminal):
```

**Comment by sfc-gh-zhyao** [comment]
I see the logic, is_terminal is just to track if the node is good for expand or not

**Comment by Chen-GX** [comment]
Yes, you are right. We won't choose a terminal node again in our released code, because we want to explore more unterminal nodes. Of course, you can delete `and (not node.is_terminal)`.
