### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by sfc-gh-zhyao** [MARIO-Math-Reasoning/Super_MARIO#22]
For this https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/agents/mcts.py#L78-L95

the logic should be (pseudo code)
```
For-loop to get the best puct

Based on the puct, loop the children again to get the best
```

The current logic's issue (maybe you put sort somewhere else):
puct = [0,1. 0.2, 0.3] then all three children will be selected

**Comment by Chen-GX** [comment]
We will randomly select one node, when more than 2 node have the same `best puct`.

**Comment by sfc-gh-zhyao** [comment]
in you current logic, it wont select the best puct. When we visit 0.1, 0.1 > -100, so it will be selected in the random list, then for the 0.2, same logic, 0.2 > 0.1, then it gets inserted into list. ...

so you final setting will be random.select([0.1, 0.2, 0.3])

**Comment by Chen-GX** [comment]
Please see https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/agents/mcts.py#L91-L93

**Comment by Chen-GX** [comment]
Please see https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/agents/mcts.py#L91-L93

**Comment by Chen-GX** [comment]
We will only maintain an optimal list with best puct.
