### ISSUE TITLE
What's the training data

### ISSUE THREAD

**Issue by sjtuytc** [MARIO-Math-Reasoning/Super_MARIO#23]
Hi, thanks for open-sourcing this excellent work.
I want to ask where is the JSON for training file; it seems that the round3_training_data.json has no such a key called 'question'.

**Comment by Chen-GX** [comment]
`round3_training_data.json` is prepared for sft, not for sampling in MCTS.
You should prepare the reasoning dataset, such as GSM8K and MATH (question and answer) for sampling, which is public available.
