### ISSUE TITLE
Which model should be used for the sampling of the first round of MCTS training data?

### ISSUE THREAD

**Issue by nomadlx** [MARIO-Math-Reasoning/Super_MARIO#27]
I think that the `deepseek-math-7b-base-value` model with a random value head added through `scripts/save_value_head.py` should be used. However, in actuality, when I set it up this way, it leads to the following error. 
```
OSError: Can't load tokenizer for '/xxx/model/deepseek-math-7b-base-value'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/xxx/model/deepseek-math-7b-base-value' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
```

So I switched to the original `deepseek-math-7b-base` model instead. Although it ran this time, since all the values were -1.0, the number of valid_solvers was 0, and the sampling process terminated in the first round. I don't think this is what was expected. 

How should I correctly set up the model to be used for the first round of sampling?

This is the directory of the deepseek-math-7b-base-value model:
```bash
config.json 
deepseek-math-7b-base 
value_head.pth
```

**Comment by nomadlx** [comment]
Is it correct to replace the corresponding files in the `deepseek-math-7b-base` directory with the newly generated `config.json` and `value_head.pth`?

**Comment by Chen-GX** [comment]
I apologize for the inconvenience. There were some bugs in `save_value_head.py` which have now been fixed.

Could you please try the updated version and let me know if it works properly now? Thank you for bringing this to our attention.

**Comment by Chen-GX** [comment]
The newly generated `config.json` and `value_head.pth` should be in the file `deepseek-math-7b-base`.
