### ISSUE TITLE
What is the "P" in each step?

### ISSUE THREAD

**Issue by ljb121002** [MARIO-Math-Reasoning/Super_MARIO#30]

**Comment by ljb121002** [comment]
For example, "P": 0.950430021915545, "Q": 1.0

**Comment by Chen-GX** [comment]
Sorry, I don't catch your question.

**Comment by ljb121002** [comment]
Sorry I typed the title wrong, just edited. I want to ask the meaning of "P" in each step of the answer. Thanks

**Comment by Chen-GX** [comment]
"P" is the prior distribution of the generated text in this step, i.e., $\pi_{\theta}(a_t|s_t)$.

**Comment by ljb121002** [comment]
Thank you!
