### ISSUE TITLE
MCTS training data generation in round1

### ISSUE THREAD

**Issue by platoonpluto** [MARIO-Math-Reasoning/Super_MARIO#9]
@lovecambi  It seems that during mcts training data generation in round 1, no "Final Answer:" will be generated by LLM?

`# Checkpoint Initialization is required by adding value head
python solver_demo.py \
--custom_cfg configs/mcts_round1.yaml \
--qaf ../MARIO_EVAL/data/math_testset_annotation.json
`

[max_solver_steps is set to 1 by default](https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/solver.py#L189), so LLM generation will stops at "Observation:"?

**Comment by lovecambi** [comment]
> @lovecambi It seems that during mcts training data generation in round 1, no "Final Answer:" will be generated by LLM?
> 
> `# Checkpoint Initialization is required by adding value head python solver_demo.py \ --custom_cfg configs/mcts_round1.yaml \ --qaf ../MARIO_EVAL/data/math_testset_annotation.json `
> 
> [max_solver_steps is set to 1 by default](https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/solver.py#L189), so LLM generation will stops at "Observation:"?

You are correct. I just updated the `mcts_round1.yaml`. According to our experience, the iterations can range from 30 to 60 for difficulty levels.

**Comment by lovecambi** [comment]
> > @lovecambi It seems that during mcts training data generation in round 1, no "Final Answer:" will be generated by LLM?
> > `# Checkpoint Initialization is required by adding value head python solver_demo.py \ --custom_cfg configs/mcts_round1.yaml \ --qaf ../MARIO_EVAL/data/math_testset_annotation.json `
> > [max_solver_steps is set to 1 by default](https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/mcts_math/solver.py#L189), so LLM generation will stops at "Observation:"?
> 
> You are correct. I just updated the `mcts_round1.yaml`.

According to our experience, the iterations can range from 30 to 60 for difficulty levels.
